server:
  port: 8081

database:
  host: localhost
  port: 5432
  user: waltertaya
  password: Walter_8236!
  dbname: saas_billing_db
  sslmode: disable

jwt:
  secret: c39eaa8c-dca9-47dc-a928-3a1624aaa5c2
